In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
%cd /content/drive/MyDrive/ML-Bitirme-Projesi

/content/drive/MyDrive/ML-Bitirme-Projesi


In [ ]:
!ls

'Başvuru Dosyası'   data  'En iyi 3 model'  'İmage Classification.ipynb'  'Veri Hazırlıgı.ipynb'


In [ ]:
#GPU test ve device isimleri
import tensorflow as tf
tf.test.gpu_device_name()

# from tensorflow.python.client import device_lib
#device_lib.list_local_devices()

'/device:GPU:0'

In [ ]:
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.optimizers import RMSprop
from keras import backend as K
from keras.src.callbacks import History
from keras.optimizers import Adam


In [ ]:
#giris olarak verilecek görüntülerin boyutları

img_width , img_height = 224 , 224

# train ve validation için veriyolu
train_data_yolu = '/content/drive/MyDrive/ML-Bitirme/data/train'
validation_data_yolu = '/content/drive/MyDrive/ML-Bitirme/data3validation'

train_ornek_sayisi = 2400
validation_ornek_sayisi = 600
epochs = 50
batch_size = 12 # her seferinde işleme alınacak veri sayısı

# train_ornek_sayisi , validation_ornek sayisi ile  batch_size tam bölünmeli


if K.image_data_format() == 'channels_first':
    input_shape = (3, img_width, img_height)
else:
    input_shape = (img_width, img_height, 3)

In [ ]:
# model oluşturma
# Model Olusturalimmodel = Sequential()
model = Sequential()
# Giris katmani ve Conv1
model.add(Conv2D(32, (3, 3), input_shape=input_shape))  # 32 filtre
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))  # 2x2 lisst

# Conv2
model.add(Conv2D(32, (5, 5)))
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv3
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Flatten Duzlestirme
model.add(Flatten())

# FC (Fully Connected Layer Olusturuluyor) Dense =FC
model.add(Dense(128)) #64 tane input
model.add(Activation('relu'))
model.add(Dropout(0.5))  # Dropout Factorization 64 girişin yarısını kapat
#sınıf sayısı binary sınıflama için Dense(1)
model.add(Dense(6))

model.add(Activation('sigmoid'))
 #optimizer = RMSprop(learnin_rate=0.05)

#derleme
model.compile(loss='binary_crossentropy',optimizer='rmsprop',metrics=['accuracy'])




In [ ]:
# model 2
model = Sequential()

# Conv1
model.add(Conv2D(64, (3, 3), input_shape=(224, 224, 3)))
model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv2
model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv3
model.add(Conv2D(256, (3, 3)))
model.add(Activation('relu'))
model.add(Conv2D(256, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv4
model.add(Conv2D(512, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Flatten
model.add(Flatten())

# Fully Connected Layers
model.add(Dense(128))
model.add(Activation('relu'))
model.add(Dropout(0.5))


# Output Layer
model.add(Dense(6))
model.add(Activation('sigmoid'))

# Compile
model.compile(loss='binary_crossentropy',
              optimizer=RMSprop(learning_rate=0.001),
              metrics=['accuracy'])

In [ ]:
# model 3


model = Sequential()

# Conv1
model.add(Conv2D(32, (3, 3), input_shape=(224, 224, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv2
model.add(Conv2D(64, (5, 5)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv3
model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Flatten
model.add(Flatten())

# Fully Connected Layers
model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dropout(0.5))

# Output Layer
model.add(Dense(6))
model.add(Activation('sigmoid'))
optimizer = RMSprop(learning_rate=0.0001)
# Compile
model.compile(loss='binary_crossentropy',optimizer=optimizer,metrics=['accuracy'])


In [ ]:
#model 4


model = Sequential()

# Conv1
model.add(Conv2D(32, (3, 3), input_shape=(224, 224, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv2
model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv3
model.add(Conv2D(128, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(128, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv4
model.add(Conv2D(256, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(256, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Flatten
model.add(Flatten())

# Fully Connected Layers
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))

# Output Layer
model.add(Dense(6))
model.add(Activation('sigmoid'))

# Compile
model.compile(loss='binary_crossentropy',
              optimizer=Adam(learning_rate=0.001),
              metrics=['accuracy'])

# Modelin özetini yazdır
model.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_54 (Conv2D)          (None, 224, 224, 32)      896       
                                                                 
 activation_76 (Activation)  (None, 224, 224, 32)      0         
                                                                 
 conv2d_55 (Conv2D)          (None, 224, 224, 32)      9248      
                                                                 
 activation_77 (Activation)  (None, 224, 224, 32)      0         
                                                                 
 max_pooling2d_38 (MaxPooli  (None, 112, 112, 32)      0         
 ng2D)                                                           
                                                                 
 conv2d_56 (Conv2D)          (None, 112, 112, 64)      18496     
                                                     

In [ ]:
# model 5
model = Sequential()

# Conv1
model.add(Conv2D(64, (3, 3), input_shape=(224, 224, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv2
model.add(Conv2D(128, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(128, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv3
model.add(Conv2D(256, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(256, (3, 3), padding='same'))
model.add(Activation('relu'))


# Conv4
model.add(Conv2D(512, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(512, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv5
model.add(Conv2D(512, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(512, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Flatten
model.add(Flatten())

# Fully Connected Layers
model.add(Dense(128))
model.add(Activation('relu'))
model.add(Dropout(0.5))


# Output Layer
model.add(Dense(6))
model.add(Activation('sigmoid'))

# Compile
model.compile(loss='binary_crossentropy',
              optimizer=RMSprop(learning_rate=0.001),
              metrics=['accuracy'])

# Modelin özetini yazdır
model.summary()

Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_62 (Conv2D)          (None, 224, 224, 64)      1792      
                                                                 
 activation_87 (Activation)  (None, 224, 224, 64)      0         
                                                                 
 conv2d_63 (Conv2D)          (None, 224, 224, 64)      36928     
                                                                 
 activation_88 (Activation)  (None, 224, 224, 64)      0         
                                                                 
 max_pooling2d_42 (MaxPooli  (None, 112, 112, 64)      0         
 ng2D)                                                           
                                                                 
 conv2d_64 (Conv2D)          (None, 112, 112, 128)     73856     
                                                     

In [ ]:
#model 6
model = Sequential()


# Conv1
model.add(Conv2D(64, (3, 3), input_shape=(224, 224, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv2
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv3
model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv4
model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Flatten
model.add(Flatten())

# Fully Connected Layer
model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dropout(0.5))


# Output Layer
model.add(Dense(6))
model.add(Activation('sigmoid'))

# Compile
model.compile(loss='binary_crossentropy',
              optimizer=Adam(learning_rate=0.001),
              metrics=['accuracy'])
model.summary()

Model: "sequential_14"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_76 (Conv2D)          (None, 222, 222, 64)      1792      
                                                                 
 activation_105 (Activation  (None, 222, 222, 64)      0         
 )                                                               
                                                                 
 max_pooling2d_50 (MaxPooli  (None, 111, 111, 64)      0         
 ng2D)                                                           
                                                                 
 conv2d_77 (Conv2D)          (None, 109, 109, 64)      36928     
                                                                 
 activation_106 (Activation  (None, 109, 109, 64)      0         
 )                                                               
                                                     

In [ ]:
#model 7


model = Sequential()

# Conv1
model.add(Conv2D(64, (5, 5), input_shape=(224, 224, 3), padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv2
model.add(Conv2D(128, (5, 5), padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv3
model.add(Conv2D(256, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Flatten
model.add(Flatten())

# Fully Connected Layers
model.add(Dense(32))
model.add(Activation('relu'))
model.add(Dropout(0.5))

# Output Layer
model.add(Dense(6, activation='sigmoid'))

# Compile
model.compile(loss='binary_crossentropy', optimizer=Adam(learning_rate=0.001), metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 224, 224, 64)      4864      
                                                                 
 activation (Activation)     (None, 224, 224, 64)      0         
                                                                 
 max_pooling2d (MaxPooling2  (None, 112, 112, 64)      0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 112, 112, 128)     204928    
                                                                 
 activation_1 (Activation)   (None, 112, 112, 128)     0         
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 56, 56, 128)       0         
 g2D)                                                   

In [ ]:
#model 8

model = Sequential()


# Conv1
model.add(Conv2D(64, (3, 3), input_shape=(224, 224, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv2
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv3
model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv4
model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Flatten
model.add(Flatten())

# Fully Connected Layer
model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dropout(0.5))


# Output Layer
model.add(Dense(6))
model.add(Activation('sigmoid'))

# Compile
model.compile(loss='binary_crossentropy',
              optimizer=Adam(learning_rate=0.001),
              metrics=['accuracy'])
model.summary()

In [ ]:
#model 9

model = Sequential()


# Conv1
model.add(Conv2D(128, (3, 3), input_shape=(224, 224, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv2
model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv3
model.add(Conv2D(256, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv4
model.add(Conv2D(256, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Flatten
model.add(Flatten())

# Fully Connected Layer
model.add(Dense(128))
model.add(Activation('relu'))
model.add(Dropout(0.5))



# Output Layer
model.add(Dense(6))
model.add(Activation('sigmoid'))

# Compile
model.compile(loss='binary_crossentropy',
              optimizer=Adam(learning_rate=0.001),
              metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 222, 222, 128)     3584      
                                                                 
 activation (Activation)     (None, 222, 222, 128)     0         
                                                                 
 max_pooling2d (MaxPooling2  (None, 111, 111, 128)     0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 109, 109, 128)     147584    
                                                                 
 activation_1 (Activation)   (None, 109, 109, 128)     0         
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 54, 54, 128)       0         
 g2D)                                                   

In [ ]:
#model 10
model = Sequential()


# Conv1
model.add(Conv2D(64, (3, 3), input_shape=(224, 224, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv2
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv3
model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv4
model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Flatten
model.add(Flatten())

# Fully Connected Layer
model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dropout(0.5))


# Output Layer
model.add(Dense(6))
model.add(Activation('sigmoid'))

# Compile
model.compile(loss='binary_crossentropy',
              optimizer=RMSprop(),
              metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_4 (Conv2D)           (None, 222, 222, 64)      1792      
                                                                 
 activation_6 (Activation)   (None, 222, 222, 64)      0         
                                                                 
 max_pooling2d_4 (MaxPoolin  (None, 111, 111, 64)      0         
 g2D)                                                            
                                                                 
 conv2d_5 (Conv2D)           (None, 109, 109, 64)      36928     
                                                                 
 activation_7 (Activation)   (None, 109, 109, 64)      0         
                                                                 
 max_pooling2d_5 (MaxPoolin  (None, 54, 54, 64)        0         
 g2D)                                                 

In [ ]:
#model 11
model = Sequential()


# Conv1
model.add(Conv2D(64, (3, 3), input_shape=(224, 224, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv2
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv3
model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv4
model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Flatten
model.add(Flatten())

# Fully Connected Layer
model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dropout(0.5))


# Output Layer
model.add(Dense(6))
model.add(Activation('sigmoid'))

# Compile
model.compile(loss='binary_crossentropy',
              optimizer=Adam(learning_rate=0.001),
              metrics=['accuracy'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_12 (Conv2D)          (None, 222, 222, 64)      1792      
                                                                 
 activation_18 (Activation)  (None, 222, 222, 64)      0         
                                                                 
 max_pooling2d_12 (MaxPooli  (None, 111, 111, 64)      0         
 ng2D)                                                           
                                                                 
 conv2d_13 (Conv2D)          (None, 109, 109, 64)      36928     
                                                                 
 activation_19 (Activation)  (None, 109, 109, 64)      0         
                                                                 
 max_pooling2d_13 (MaxPooli  (None, 54, 54, 64)        0         
 ng2D)                                                

In [ ]:
# Model oluşturma - Model 5
model = Sequential()

# Giriş katmanı ve Conv1
model.add(Conv2D(64, (3, 3), input_shape=input_shape))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv2
model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv3
model.add(Conv2D(256, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Düzleştirme
model.add(Flatten())

# FC (Fully Connected Layer)
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))

# Çıkış katmanı
model.add(Dense(6))  # 6 sınıf için çıkış katmanı
model.add(Activation('sigmoid'))

# Derleme
optimizer = Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])

model.summary()

Model: "sequential_14"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_43 (Conv2D)          (None, 222, 222, 64)      1792      
                                                                 
 activation_65 (Activation)  (None, 222, 222, 64)      0         
                                                                 
 max_pooling2d_40 (MaxPooli  (None, 111, 111, 64)      0         
 ng2D)                                                           
                                                                 
 conv2d_44 (Conv2D)          (None, 109, 109, 128)     73856     
                                                                 
 activation_66 (Activation)  (None, 109, 109, 128)     0         
                                                                 
 max_pooling2d_41 (MaxPooli  (None, 54, 54, 128)       0         
 ng2D)                                               

In [ ]:
#model 6--------
model = Sequential()


# Conv1
model.add(Conv2D(64, (3, 3), input_shape=(224, 224, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv2
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv3
model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv4
model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Flatten
model.add(Flatten())

# Fully Connected Layer
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))


# Output Layer
model.add(Dense(6))
model.add(Activation('sigmoid'))

# Compile
model.compile(loss='binary_crossentropy',
              optimizer=Adam(learning_rate=0.001),
              metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 222, 222, 64)      1792      
                                                                 
 activation (Activation)     (None, 222, 222, 64)      0         
                                                                 
 max_pooling2d (MaxPooling2  (None, 111, 111, 64)      0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 109, 109, 64)      36928     
                                                                 
 activation_1 (Activation)   (None, 109, 109, 64)      0         
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 54, 54, 64)        0         
 g2D)                                                   

In [ ]:
# Model oluşturma - Model 6-----
model = Sequential()

# Giriş katmanı ve Conv1
model.add(Conv2D(32, (3, 3), input_shape=input_shape))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv2
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Düzleştirme
model.add(Flatten())

# FC (Fully Connected Layer)
model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dropout(0.5))

# Çıkış katmanı
model.add(Dense(6))  # 6 sınıf için çıkış katmanı
model.add(Activation('sigmoid'))

# Derleme
optimizer = RMSprop(learning_rate=0.001)
model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])


In [ ]:
# Model oluşturma - Model 5
model = Sequential()

# Giriş katmanı ve Conv1
model.add(Conv2D(64, (3, 3), input_shape=input_shape))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv2
model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Conv3
model.add(Conv2D(256, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Düzleştirme
model.add(Flatten())

# FC (Fully Connected Layer)
model.add(Dense(1024))
model.add(Activation('relu'))
model.add(Dropout(0.5))

# Çıkış katmanı
model.add(Dense(6))  # 6 sınıf için çıkış katmanı
model.add(Activation('sigmoid'))

# Derleme
optimizer = Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_4 (Conv2D)           (None, 222, 222, 64)      1792      
                                                                 
 activation_6 (Activation)   (None, 222, 222, 64)      0         
                                                                 
 max_pooling2d_4 (MaxPoolin  (None, 111, 111, 64)      0         
 g2D)                                                            
                                                                 
 conv2d_5 (Conv2D)           (None, 109, 109, 128)     73856     
                                                                 
 activation_7 (Activation)   (None, 109, 109, 128)     0         
                                                                 
 max_pooling2d_5 (MaxPoolin  (None, 54, 54, 128)       0         
 g2D)                                                 

In [ ]:

# Train islemi icin kullanilan verileri cogaltiyor
train_datalar = ImageDataGenerator(
    rescale=1. / 255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True)

# datalar = ImageDataGenerator(rotation_range=40, width_shift_range=0.2, height_shift_range=0.2,
# shear_range=0.2, zoom_range=0.2, horizontal_flip=True, fill_mode='nearest')

# Test islemi icin goruntuleri rescale boyutlandirma yapiyor
test_datalar = ImageDataGenerator(rescale=1. / 255)

train_generator = train_datalar.flow_from_directory(
    train_data_yolu,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='categorical')

# Binary classification (ikili siniflama) : class_mode='binary'
# Multiclass (Coklu sinif) : class_mode='categorical'

validation_generator = test_datalar.flow_from_directory(
    validation_data_yolu,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='categorical')

# Binary classification (ikili siniflama) : class_mode='binary'
# Multiclass (Coklu sinif) : class_mode='categorical'

Found 2400 images belonging to 6 classes.
Found 600 images belonging to 6 classes.


In [ ]:
# Modelin Egitimi
history = model.fit(
    train_generator,
    steps_per_epoch=train_ornek_sayisi // batch_size,
    epochs=epochs,
    validation_data=validation_generator,
    validation_steps=validation_ornek_sayisi // batch_size)

In [ ]:
# ağırlıkları kaydetme
model.save_weights('e50-batch12-ac80.00-(E-Model6best).h5')

In [ ]:
train_loss = history.history['loss']
val_loss = history.history['val_loss']
train_accuracy = history.history['accuracy']
val_accuracy = history.history['val_accuracy']

# Bu metrikleri görselleştirelim
import matplotlib.pyplot as plt

# Doğruluk grafiği
plt.plot(train_accuracy, label='Eğitim Doğruluğu')
plt.plot(val_accuracy, label='Doğrulama Doğruluğu')
plt.xlabel('Epoch')
plt.ylabel('Doğruluk')
plt.legend()
plt.show()


In [ ]:
!ls

 data	 fazlalik    first_try.h5		   second_try.h5
 data2	 fazlalik2  'İmage Classification.ipynb'   test_try.h5


In [ ]:
%cd /content/drive/MyDrive/ML-Bitirme-Projesi/data/test/agac_test/saglıklı_agac_test

/content/drive/MyDrive/ML-Bitirme-Projesi/data/test/agac_test/saglıklı_agac_test


In [ ]:
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
import numpy as np
import os


model.load_weights('/content/drive/MyDrive/ML-Bitirme-Projesi/En iyi 3 model/E-model5-Fc1024/e50-batch12-ac96.29-(Model5best-FC1024).h5')
for filename in os.listdir():
  img = load_img(filename, grayscale=False, color_mode='rgb', target_size=(img_width, img_height))
  # img = load_img('deneme.jpg', False, (img_width, img_height))
  x = img_to_array(img)  # Numpy kutuphanesi ile bir diziye donusturuldu: shape (3, 224, 224)
  prediction = model.predict(x.reshape((1, img_width, img_height, 3)), batch_size=12, verbose=0)  # (1, 224, 224, 3)
  print(prediction)


[[1. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0.]]
[[0. 1. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0.]]
